# -*- coding: utf-8 -*-
"""ML_au11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10-oBhZdea_YacCiTvWVwcTwOi2U-dbkU

1. Load the dataset
2. Explore the dataset
3. Handle missing values ( if any )
4. Check duplicates
5. Calculate mean, median, std
6. Detect Outliers( IQR, LL, UL )
7. Normalize numerical features
8. Standardize numerical features
9. Save the clean dataset

1. Remove unnecessary features
2. Which features are categorical and which are numerical ?
3. Update a value of dataset by selecting a row or column
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""# Load the dataset"""

import seaborn as sns
df = sns.load_dataset('titanic')

df_backup = df.copy()

"""# Separate the label from the Features : to maintain the problem as a classification problem

if the label remains the part of the dataset while processinf/polishing it, the values of labels would also get affected during the Standardiazation/Nomalization step

alt approach : keep label as part of thhe dataset and drop it from this features dataframe when all the processing is done, ans retrieve it as separate dataframe from the df_copy
"""

df_target = df[ "survived" ]

df_target.head()

df = df.drop( "survived", axis=1 )

df.head(  )

"""# Explore the dataset"""

df.head()
#df = pd.DataFrame( df ) - not required yet

print(df.columns)

df.info()

df.describe()

df.isnull().sum()

col_corr = {  }
for col in df.columns:
  col_corr[col] = len(df[col])

print(col_corr)

max_samples = 0
for key in col_corr.keys():
  if( col_corr[key] > max_samples ) :
    max_samples = col_corr[key]
    #max_col = key

print(max_samples)

"""# Q1) Which features are categorical and which are numerical ?

Ans :

*   Categorical


1. sex
2. embarked
3. who
4. deck
5. embark_town
6. alive


*   Numerical


1. survived
2. pclass
3. age
4. sibsp
5. parch
6. fare
7. class
8. adult_male
9. alone

# Q2) Remove unnecessary features

1. since "sex" and "who" columns give information about the same data,
either of them can be removed.
"""

df = df.drop("who", axis=1)
df.head()

"""2. since "survived" and "alive" columns give information about the same data,
either of them can be removed;
removing "alive" is more preferrable since "survived" is already present in one hot encoding format

"""

df = df.drop("alive", axis=1)
df.head()

df = df.drop("adult_male", axis=1)
df.head()

df = df.drop("deck", axis=1)
df.head()

#df = df.drop("embark_town", axis=1)
#df.head()

"""3. since we cannot calculate mean or other operations for string or categorical
data ( columns "embark_town" and "deck" ) , we will replace the null values with a substitute string; say 'U' **discontinued**
"""

#df["embark_town"].replace( np.nan, "U", inplace=True )
#df["deck"].replace( np.nan, "U", inplace=True )

#df["deck"].fillna( "U", inplace=True )
#df.head()

df.info()

"""replacing null values in "age" column with mean/avg value"""

df["age"] = df["age"].fillna( df["age"].mean() )

df.info()

"""Ordinal Encoding for "class" column/attribute"""

from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder( categories=[ ["Third", "Second", "First"] ]  )

df_class = df[ "class" ]

df["class"] = encoder.fit_transform( df_class.values.reshape(-1,1) )

"""Scaling the numerical features using StandardScaler"""

df.info()

df_without_scaling = df.copy()

from sklearn.preprocessing import StandardScaler

scaler_instance = StandardScaler()

df.head()

cols_to_be_scaled = []

for col in df.columns :
  if(  ( (df[col].dtype == int) or (df[col].dtype == float )) and (df[col].max() > 1))  :
    cols_to_be_scaled.append( col )

print(cols_to_be_scaled)

df.head()

#df = scaler_instance.fit_transform( df[cols_to_be_scaled] )
#df = pd.DataFrame( df )

for col in cols_to_be_scaled :
  df[col] = scaler_instance.fit_transform( df[col].values.reshape(-1,1) )

df.head()

"""One Hot Encoding for categorical data"""

df = pd.get_dummies( df, columns=["sex"] )
df.head()

df = pd.get_dummies( df, columns=["embark_town"] )
df.head()

df = pd.get_dummies( df, columns=["embarked"] )
df.head()

#df = pd.get_dummies( df, columns=["deck"] )
#df.head()

#df[ "alone" ] = df[ "alone" ].astype( int )
#df.head()

for col in df.columns :
  if( df[col].dtype == bool ) :
    df[col] = df[col].astype(int)

df.head()

max_list = []
min_list = []

for col in df.columns :
  max_list.append( df[col].max() )
  min_list.append( df[col].min() )

plt.plot( np.arange( len(max_list)), max_list )
plt.show()

plt.plot( np.arange( len(min_list)), min_list )
plt.show()

"""# Splitting polished dataset into training and test datasets"""

#alt approach :
# X = df.drop( "survived" )
# y = df_copy["survived"]

df_target.head()

df.head(  )

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( df, df_target, test_size=0.2, random_state=42 )

print( len(df_target) )
print( len(y_train) )
print( len(y_test) )

"""# Fitting a Logistic Regression model on the (X_train, y_train) to predict y_test using the values of X_test"""

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit( X_train, y_train )

y_pred = model.predict( X_test )

"""# use **accuracy_score** metric to evaluate mismatch between actual labels and the predicted labels"""

from sklearn.metrics import accuracy_score

print( accuracy_score( y_pred, y_test ) )

"""# Plot a scatter plot to display difference between the actual labels and the predicted labels"""

from matplotlib import pyplot as plt

plt.scatter( np.arange( len(y_pred) ), y_pred, color="red" )
plt.scatter( np.arange( len(y_test) ), y_test, color="blue" )
plt.show()

#plt.scatter( np.arange(20), y_pred[:20], color="red" )
#plt.scatter( np.arange(20), y_test[:20], color="blue" )
#plt.show()

#plt.scatter( np.arange(20,40), y_pred[20:40], color="red" )
#plt.scatter( np.arange(20,40), y_test[20:40], color="blue" )
#plt.show()

print( np.array(y_test) )

mismatch = []
matched_count = 0
mismatched_count = 0

for i in range( len(y_pred) ) :
  val = int(y_pred[i] == np.array(y_test)[i])

  if( val == 0 ) :
    mismatched_count += 1
  else :
    matched_count += 1
  mismatch.append( val )

perc = (matched_count/len(y_pred))*100
formatted_perc = (str(perc))[ : 5 ]

print( formatted_perc )

"""# use Histogram for visual description of accuracy_score"""

plt.hist( mismatch )
plt.title( "matches : " + formatted_perc + "%" )
plt.show()

#df = scaler_instance.fit_transform(df)
#df = pd.DataFrame( df, columns=df_without_scaling.columns )

"""# use pie chart for visual description of accuracy_score"""

categories = ['matched', 'mismatched']
quantities = [matched_count, mismatched_count]

slice_colors = ['blue', 'red']
plt.pie(
    quantities,
    labels=categories,
    autopct='%1.2f%%',
    colors=slice_colors,
)

plt.title('accuracy distribution', fontsize=16, fontweight='bold')
plt.show()