# -*- coding: utf-8 -*-
"""ML_aug14_HousePricing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_m4cyjUzu7wfSWJBh2vsGDuS0w_DmhQM

Import the HousePricing dataset and required libraries
"""

path = "//content/train_28jul (1).csv"

import pandas as pd
df = pd.read_csv(path)

import matplotlib.pyplot as plt

import numpy as np

"""Create backup copy of the dataset"""

df_backup = df.copy()

"""Perform preprocessing on a specific column ( "LotArea" )"""

target = df[ 'LotArea' ]
median_value = target.median()

plt.plot( target )
plt.axhline( median_value, color = 'red' )
plt.show()

sorted_target =  np.sort( target )
plt.plot( sorted_target )
plt.axhline( median_value, color = 'red' )
plt.show()

target.describe().loc[ ['25%', '50%', '75%'] ]

q1 = target.quantile( 0.25 )
q2 = target.quantile( 0.5 )
q3 = target.quantile( 0.75 )

iqr = q3 - q1
print( f"iqr : {iqr}" )

LL = q1 - 1.5 * iqr
UL = q3 + 1.5 * iqr

print( f"lower limit : { LL }" )
print( f"upper limit : { UL }" )

lower_outlier_count = target[ target < LL ]
upper_outlier_count = target[ target > UL ]

print( f"lower outliers : {len(lower_outlier_count)}" )
print( f"upper outliers : {len(upper_outlier_count)}" )

valid_values = target[ (target > LL) & (target < UL) ]
print( f"valid values : {len(valid_values)}" )

valid_values.describe()

plt.subplot( 1,2,1 )
plt.plot( sorted_target )
plt.axhline( LL, color = 'black' )
plt.axhline( q1, color = 'orange' )
plt.axhline( median_value, color = 'red' )
plt.axhline( q3, color = 'orange' )
plt.axhline( UL, color = 'black' )
plt.title( "bounds on line graph" )

plt.subplot( 1,2,2 )
plt.hist( sorted_target )
plt.axvline( LL, color = 'black' )
plt.axvline( UL, color = 'black' )
plt.axvline( median_value, color = 'red' )
plt.axvline( q1, color = 'orange' )
plt.axvline( q3, color = 'orange' )
plt.title( "distribution" )

plt.show()

plt.subplot( 1,2,1 )
plt.plot( valid_values )
plt.axhline( LL, color = 'black' )
plt.axhline( UL, color = 'black' )
plt.axhline( median_value, color = 'red' )
plt.axhline( q1, color = 'orange' )
plt.axhline( q3, color = 'orange' )
plt.title( "bounds on line graph" )

plt.subplot( 1,2,2 )
plt.hist( valid_values )
plt.axvline( LL, color = 'black' )
plt.axvline( UL, color = 'black' )
plt.axvline( median_value, color = 'red' )
plt.axvline( q1, color = 'orange' )
plt.axvline( q3, color = 'orange' )
plt.title( "distribution" )

plt.show()

"""Preview the dataset again to perform further polishing"""

dataset = df.copy()

dataset.head()

dataset.info()

"""Seperate the features and target from the dataset"""

dataset = dataset.drop( 'Id', axis = 1 )

y = dataset["SalePrice"]
X = dataset.drop("SalePrice", axis = 1)

"""Obtain the list of columns with null-values"""

#finding max len of an attribute
len_of_X = len( X )
print( f"dataset has { len_of_X } samples " )

cols_with_less_samples = {}

for col in X.columns :
  temp_col = X[col]
  temp_len = len( temp_col.dropna() )
  #print( len(temp_col) )
  if ( temp_len < len_of_X ) :
    #print( f"len of {col} is {len(col)}" )
    cols_with_less_samples[col] = temp_len

print( cols_with_less_samples )

"""Drop the columns with very few not null values"""

#assume 80% margin for filling null values, drop others

margin = 0.8 * len_of_X

for col in cols_with_less_samples :
  if ( cols_with_less_samples[col] < margin ) :
    X.drop( col, axis = 1, inplace = True )

X.head()

X.info()

X.describe()

"""Fill the null values with mean for numeric columns

"""

cols_with_less_samples = {}

for col in X.columns :
  temp_col = X[col]
  temp_len = len( temp_col.dropna() )
  #print( len(temp_col) )
  if ( temp_len < len_of_X ) :
    #print( f"len of {col} is {len(col)}" )
    cols_with_less_samples[col] = temp_len

print( cols_with_less_samples )

for col in cols_with_less_samples :
  if ( X[col].dtype == 'int64' or X[col].dtype == 'float64' ) :
    temp_col = X[col]
    temp_mean_value = temp_col.mean()
    X[col] = temp_col.fillna(  temp_mean_value )

X.info()

X.describe()

"""Perform Standardization on numeric columns"""

from sklearn.preprocessing import StandardScaler

scaler_instance = StandardScaler()

for col in X.columns :
  temp_col = X[col]
  if ( temp_col.dtype == 'int64' or temp_col.dtype == 'float64' ) :
    temp_col = temp_col.values.reshape( -1,1 )
    temp_col = scaler_instance.fit_transform( temp_col )
    X[col] = temp_col

"""Remove outliers from the newly obtained columns

"""

for col in X.columns :
  temp_col = X[col]
  if ( temp_col.dtype == 'int64' or temp_col.dtype == 'float64' ) :
    q1 = temp_col.quantile( 0.25 )
    q2 = temp_col.quantile( 0.5 )
    q3 = temp_col.quantile( 0.75 )
    iqr = q3 - q2
    LL = q2 - 1.5*iqr
    UL = q3 + 1.5*iqr
    temp_col = temp_col[ (temp_col > LL) & (temp_col < UL) ]
    X[col] = temp_col

X.info()

X.describe()

"""Drop the columns with zero eligible values"""

for col in X :
  temp_col = X[col]
  if ( temp_col.dtype == 'int64' or temp_col.dtype == 'float64' ) :
    if( ( len(temp_col) - temp_col.isnull().sum()) == 0  ) :
      X = X.drop( col, axis = 1 )

X.info()

"""Drop the columns with very few not-null values after removing outliers"""

cols_with_less_samples = {}

for col in X.columns :
  temp_col = X[col]
  temp_len = len( temp_col.dropna() )
  #print( len(temp_col) )
  if ( temp_len < len_of_X ) :
    #print( f"len of {col} is {len(col)}" )
    cols_with_less_samples[col] = temp_len

print( cols_with_less_samples )

#assume 80% margin for filling null values, drop others

margin = 0.8 * len_of_X

for col in cols_with_less_samples :
  if ( cols_with_less_samples[col] < margin ) :
    X = X.drop( col, axis = 1)

X.head()

X.info()

"""Perform ordinal encoding on eligible categorical columns ( **paused** )

Perform one hot encoding on remaining categorical columns
"""

available_cols = X.columns

for col in available_cols :
  temp_col = X[col]
  if ( temp_col.dtype == 'object' ) :
    X = pd.get_dummies( temp_col )

"""Typecast the Boolean values of OHE into integers

"""

for col in X.columns :
  temp_col = X[col]
  if ( temp_col.dtype == 'bool' ) :
    temp_col = temp_col.astype( int )
    X[col] = temp_col

"""
Split test_train"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2 )

"""

Import linear regression
"""

from sklearn.linear_model import LinearRegression

model = LinearRegression()

"""
Fit linear regression
"""

model.fit( X_train, y_train )

"""
Predict values using the model
"""

y_pred = model.predict( X_test )

"""
Evaluate the performance using suitable metric ( eg mse )"""

from sklearn.metrics import mean_squared_error

mse_score = mean_squared_error( y_pred, y_test )
print( f"mse score is { mse_score }" )

"""# Visualization of model performance

Line Graph for y_test
"""

m = model.coef_

c = model.intercept_

import matplotlib.pyplot as plt

plt.scatter( np.arange( len(y_test) ), y_test, color='blue' )
plt.axline( xy1=( 0, c ), xy2=( 1, sum(m*1) + c ), color='red' )
fmt_mse = (str(mse_score))
plt.title( fmt_mse )
plt.show()