# -*- coding: utf-8 -*-
"""pd_cut_sep08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Q8bWkfst3-42ZHgcdA59U8uA2GZ2p1f
"""

import pandas as pd
import numpy as np

!wget https://raw.githubusercontent.com/durveshcollegeid/sem5_ML/refs/heads/main/aug28/adult/adult.data

path = "/content/adult.data"

df = pd.read_csv( path )
df_backup = pd.read_csv( path )
df_backup_copy = pd.read_csv( path )

col_list = [ "age", "workclass", "fnlwgt", "education", "education-num", "marital-status", "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss", "hours-per-week", "native-country", "income" ]

df.columns = col_list
df_backup.columns = col_list
df_backup_copy.columns = col_list



"""nunique(), unique(), count()"""

df_new = df_backup
#df_new = pd.DataFrame(columns = col_list)

#for col in col_list :
#  df_new["new"+col] = df_new[col].replace( "?", np.nan )
#  df_new.drop(col)

df_new.nunique( axis=0 ) #number of unique values per column

df_new.nunique( axis=1 ) #number of unique values per row

df_new.nunique( axis=0, dropna=True ) #number of not-null unique values per column

df_new.nunique( axis=1, dropna=True ) #number of not-null unique values per row

df_new.count( axis=0) #number of not-null unique values per column

df_new.count( axis=1) #number of not-null unique values per column

#df_new["age"].unique()

"""Defining manual bins for pd.cut()"""

df_new["new_age"] = pd.cut( df_new["age"], bins=[0,11,18,45,60], labels=["Young", "Minor", "Adult", "Old"] )

df_new.head()

"""Allowing automatic bins for pd.cut()"""

df_new["auto_age"] = pd.cut( df_new["age"], bins=4, labels=["Young", "Minor", "Adult", "Old"] )

df_new.head()

"""Count comparison"""

df_new["auto_age"].nunique()

labels=["Young", "Minor", "Adult", "Old"]

print( "automatic cut" )
for x in labels :
  print( "count of " +x + " = " + str(int(df_new[ df_new["auto_age"] == x ]["auto_age"].count())) )

print( "manual cut" )
for x in labels :
  print( "count of " +x + " = " + str(int(df_new[ df_new["new_age"] == x ]["new_age"].count())) )