# -*- coding: utf-8 -*-
"""UCI_knn_aug31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12-HqctzngMADcTM8IC44_AkfHpcFAmeC

Importing the Dataset
"""

import pandas as pd
import numpy as np

path = "/content/adult.data"

df = pd.read_csv( path )
df_backup = pd.read_csv( path )

col_list = [ "age", "workclass", "fnlwgt", "education", "education-num", "marital-status", "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss", "hours-per-week", "native-country", "income" ]

df.columns = col_list
df_backup.columns = col_list

"""Drop unnecessary columns"""

df = df.drop( "fnlwgt", axis=1 )

"""OneHotEncoding"""

#targeted_cols = [ "workclass", "marital-status", "occupation", "relationship", "race", "sex", "native-country" ]
targeted_cols = [ "workclass", "education", "marital-status", "occupation", "relationship", "race", "sex", "native-country" ]

df = pd.get_dummies(df, columns=targeted_cols, dtype=int)

"""OrdinalEncoding ( skip for now )"""

#targeted_cols = [ "education" ]

#edu_values = df[ "education" ].unique( )

#edu_map = {  }

"""Splitting into features and target"""

y = df[ "income" ]
X = df.drop( "income", axis=1 )

"""Splitting into test and train"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42 )

"""Scaling Numeric data for X_train only"""

from sklearn.preprocessing import StandardScaler

for col in X_train :
  if( X[col].dtype == "int64" or X[col].dtype == "float64" ) :
    scaler = StandardScaler()
    X_train[col] = scaler.fit_transform( np.array(X_train[col]).reshape(-1,1) )

"""Importing KNN model"""

from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier( n_neighbors = 5 )

"""Importing DecisionTree model"""

from sklearn.tree import DecisionTreeClassifier

dtc_model = DecisionTreeClassifier( max_depth=3 )

"""Fitting the models on the data"""

knn_model.fit( X_train, y_train )

dtc_model.fit( X_train, y_train )

"""Obtain predicted labels of the models"""

knn_pred = knn_model.predict( X_test )

dtc_pred = dtc_model.predict( X_test )

"""Obtain accuracy scores for the models"""

from sklearn.metrics import accuracy_score

knn_acc = accuracy_score( y_test, knn_pred )

dtc_acc = accuracy_score( y_test, dtc_pred )

print( f" KNN accuracy : { knn_acc }" )

print( f" DTC accuracy : { dtc_acc }" )

"""Plot pie chart for accuracy scores"""

import matplotlib.pyplot as plt

#plt.subplot( 1, 2, 1 )
plt.pie(
    x=[ knn_acc*100, 100 - (knn_acc)*100 ],
    labels=["matched", "wrong"],
    autopct='%1.3f%%',   # Formats the percentage to 1 decimal place
    colors=[ "blue", "red" ],       # Applies custom colors
    pctdistance=0.85     # Adjusts the position of the percentage text
)
plt.title( "knn performance : accuracy score" )

plt.show()

#plt.subplot( 1, 2, 2 )
plt.pie(
    x=[ dtc_acc, 1 - dtc_acc ],
    labels=["matched", "wrong"],
    autopct='%1.3f%%',   # Formats the percentage to 1 decimal place
    colors=[ "blue", "red" ],       # Applies custom colors
    pctdistance=0.85     # Adjusts the position of the percentage text
)
plt.title( "dtc performance : accuracy score" )

plt.show()

