# -*- coding: utf-8 -*-
"""bank_marketing_sep11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hwd8X6AmoSJ2oLBeI4sBljM8eEmmvZl1

# import the required dataset ( UCI : bank marketing )
"""

import pandas as pd
import numpy as np

!wget https://raw.githubusercontent.com/durveshcollegeid/sem5_ML/refs/heads/main/sep11/bank/bank-full.csv

path  = "/content/bank-full.csv"

df = pd.read_csv( path, sep=';' )
df_backup = pd.read_csv( path, sep=';' )

"""# find missing/null values"""

df.head()

df.info()

#no missing values found in the dataset

"""# split data into features and target"""

y = df["y"]
X = df.drop( "y", axis=1 )

y = y.map( { "yes":1, "no":0 } )

"""# Perform encoding on the binary features ( value = yes/no )"""

X[ "default" ] = X[ "default" ].map( { "yes":1, "no":0 } )

X[ "housing" ] = X[ "housing" ].map( { "yes":1, "no":0 } )

X[ "loan" ] = X[ "loan" ].map( { "yes":1, "no":0 } )

"""# perform one hot encoding on features with many categories"""

one_hot_cols = [ "job", "marital", "education", "contact", "month", "poutcome" ]

for col in one_hot_cols:
  one_hot_df = pd.get_dummies( X[ col ], prefix=col )
  X = X.drop( col, axis=1 )
  X = pd.concat( [ X, one_hot_df ], axis=1 )

"""# drop the irrelevant features"""

import matplotlib.pyplot as plt

plt.hist( X["campaign"]  )

plt.hist( X["pdays"]  )

#plt.hist( X["education"]  )

"""# transforming boolean values to integers"""

for col in X.columns:
  if X[ col ].dtype == bool:
    X[ col ] = X[ col ].astype( int )

"""# split the data into training and testing dataset"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42 )

"""# find outliers for each feature in the dataset

skipped for now
"""

plt.hist( X_train["balance"]  )

#q1 = X_train["balance"].quantile( 0.25 )
#q2 = X_train["balance"].quantile( 0.50 )
#q3 = X_train["balance"].quantile( 0.75 )
#iqr = q3 - q1

#LL = q1 - 1.5*iqr
#UL = q3 + 1.5*iqr

#X_train_new = X_train[ ( X_train["balance"] > LL ) & ( X_train["balance"] < UL ) ]
#y_train_new = y_train[ ( X_train["balance"] > LL ) & ( X_train["balance"] < UL ) ]

#len( X_train_new ), len( y_train_new )

#since the data for majority of the features is either categorical (and then transformed into booleans), features other than "balance" does not contain outlier values

X_train.info()

"""# Training a decision tree model"""

from sklearn.tree import DecisionTreeClassifier

model_dct = DecisionTreeClassifier()

model_dct.fit( X_train, y_train )

"""# predicting on test data using decision tree model"""

y_pred_dct = model_dct.predict( X_test )

"""# Training a knn model"""

from sklearn.neighbors import KNeighborsClassifier

model_knn = KNeighborsClassifier(  )

model_knn.fit( X_train, y_train )

"""# predicting on test data using knn model"""

y_pred_knn = model_knn.predict( X_test )

"""# evaluating accuracy scores for the models"""

from sklearn.metrics import accuracy_score

acc_dct = accuracy_score( y_test, y_pred_dct )

print( acc_dct )

acc_knn = accuracy_score( y_test, y_pred_knn )

print( acc_knn )

"""# obtaining pie charts to visualize performance of the models"""

plt.pie( x = [ 100*(acc_dct), 100*(1-acc_dct) ], colors = ["blue", "red"], labels = [ "correct", "wrong" ], autopct='%.2f%%'  )
plt.title(  "Decision Tree performance" )

plt.pie( x = [ 100*(acc_knn), 100*(1-acc_knn) ], colors = ["blue", "red"], labels = [ "correct", "wrong" ],  autopct='%.2f%%' )
plt.title( "KNN performance" )