# -*- coding: utf-8 -*-
"""UCL_dtc_gscv_Sep04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EFWC_WF1hVGO8W9E9M3wjeyGLv9rLXER
"""

import pandas as pd
import numpy as np

#!wget https://github.com/durveshcollegeid/sem5_ML/blob/main/sep04/adult.csv

path = "/content/adult.csv"

df = pd.read_csv( path )
df_backup = pd.read_csv( path )

col_list = [ "age", "workclass", "fnlwgt", "education", "education-num", "marital-status", "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss", "hours-per-week", "native-country", "income" ]

df.columns = col_list
df_backup.columns = col_list

"""Drop unnecessary columns"""

df = df.drop( "fnlwgt", axis=1 )

"""OneHotEncoding"""

#targeted_cols = [ "workclass", "marital-status", "occupation", "relationship", "race", "sex", "native-country" ]
targeted_cols = [ "workclass", "education", "marital-status", "occupation", "relationship", "race", "sex", "native-country" ]

df = pd.get_dummies(df, columns=targeted_cols, dtype=int)

"""Splitting into features and target"""

y = df[ "income" ]
X = df.drop( "income", axis=1 )

"""Splitting into test and train"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42 )

"""Scaling Numeric data for X_train only"""

from sklearn.preprocessing import StandardScaler

for col in X_train :
  if( X_train[col].dtype == "int64" or X_train[col].dtype == "float64" ) :
    scaler = StandardScaler()
    X_train[col] = scaler.fit_transform( np.array(X_train[col]).reshape(-1,1) )

"""Importing DecisionTreeClassifier model"""

from sklearn.tree import DecisionTreeClassifier

"""Instantiating the model without any arguments"""

dtc_model =  DecisionTreeClassifier(  )

"""Define a dictionary of chosen parameters for the knn model"""

dtc_params = {
    "criterion" : ["gini", "entropy", "log_loss"],
   #"splitter" : [ "best", "random" ],
  "max_depth" : [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ],
    #"min_samples_split" : [ 2, 3, 4, 5, 6, 7, 8, 9, 10 ],
    #"min_samples_leaf" : [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ],
    "max_features" : [ "sqrt", "log2" ],
}

"""Instantiating a cross-validator based on dictionary of chosen parameters"""

from sklearn.model_selection import GridSearchCV

dtc_grid = GridSearchCV( dtc_model, dtc_params, cv=5, scoring="accuracy", n_jobs=-1 )

"""Fit the cross validator on the training data"""

dtc_grid.fit( X_train, y_train )

"""Obtain best parameters"""

print( f"Best parameters : { dtc_grid.best_params_ }" )

print( f"Best CV score : { dtc_grid.best_score_ }" )

"""Use "best estimator" to predict labels on the test data"""

dtc_best = dtc_grid.best_estimator_

y_pred = dtc_best.predict( X_test )

"""Add pie chart to visualize performance"""

from sklearn.metrics import accuracy_score

dtc_acc = accuracy_score( y_test, y_pred )

import matplotlib.pyplot as plt

#plt.subplot( 1, 2, 1 )
plt.pie(
    x=[ dtc_acc*100, 100 - (dtc_acc)*100 ],
    labels=["matched", "wrong"],
    autopct='%1.3f%%',   # Formats the percentage to 1 decimal place
    colors=[ "blue", "red" ],       # Applies custom colors
    #pctdistance=0.85     # Adjusts the position of the percentage text
)
plt.title( "dtc performance : accuracy score" )

plt.show()