# -*- coding: utf-8 -*-
"""groupby_sep09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WldhktDPcJtYRInLF7t5EEOfMr4U89Qn

# import pandas and required data
"""

import pandas as pd
import numpy as np

!wget "https://raw.githubusercontent.com/durveshcollegeid/sem5_ML/refs/heads/main/train_28jul%20(1).csv"

path = "/content/train_28jul (1).csv"

"""# create a pandas DataFrame from the csv file"""

df = pd.read_csv( path )
df_copy = pd.read_csv( path )

df.head()

df.columns

"""# use groupby for "Neighborhood" column"""

df_grouped = df.groupby('Neighborhood')

df_grouped = pd.DataFrame( df_grouped )
df_grouped.columns = ['Neighborhood', 'data']
df_grouped.head()

"""# Relation between unique values in df and shape of df_grouped"""

df['Neighborhood'].unique(), len(df['Neighborhood'].unique())

print( df.shape, df_grouped.shape )

"""# Aggregate function on grouped data"""

df_grouped_original = df.groupby('Neighborhood')

df_grouped_original['SalePrice'].mean()

df_grouped_original['SalePrice'].max()

"""# Grouping on multiple feature columns"""

df_multi_grouped = df.groupby(['Neighborhood', 'Street'] )

df_multi_grouped['SalePrice'].mean()

df_multi_grouped['SalePrice'].max()

df_multi_grouped['SalePrice'].describe()

"""# Aggregation dictionary on multiple data columns using .agg()"""

df_multidata = df.groupby( "Neighborhood" ).agg(
    {
        "SalePrice": "mean",
        'GarageCars': "max"
    }
)

df_multidata

df_multidata.describe()

"""# transform the dataframe"""

df_copy = pd.read_csv(path)

df_copy["mean_saleprice_wrt_neighbourhood"] = df.groupby("Neighborhood")["SalePrice"].transform("mean")

df_copy.head(20)